name: Publish Docker Image 🐳

on:
  workflow_run:
    workflows: ["Finalize Release ⛵"]
    types: [completed]

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Docker Image 🐳
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ✍️
        uses: actions/checkout@v4

      - name: Login to Docker Hub 🔒
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU 🔨
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 🔧
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) 💉
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alamellama/mkdocs-publisher
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build distribution 📦
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
